//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_revix
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Distributie()
        {
            this.DistributieActori = new HashSet<DistributieActori>();
        }
    
        public int IDDistributie { get; set; }
        public int ID { get; set; }
        public int IDRegizor { get; set; }
    
        public virtual Toate Toate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributieActori> DistributieActori { get; set; }
        public virtual Regizori Regizori { get; set; }
    }
}
