//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_revix
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributieActori
    {
        public int IDDistAct { get; set; }
        public int IDDistributie { get; set; }
        public int IDActor { get; set; }
        public string Rol { get; set; }
    
        public virtual Distributie Distributie { get; set; }
        public virtual Actori Actori { get; set; }
    }
}
