//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_revix
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recenzii
    {
        public int IDRecenzie { get; set; }
        public int IDUser { get; set; }
        public int ID { get; set; }
        public System.DateTime DataPublicarii { get; set; }
        public string Descriere { get; set; }
        public Nullable<int> Scor { get; set; }
    
        public virtual Utilizator Utilizator { get; set; }
        public virtual Toate Toate { get; set; }
    }
}
