//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_revix
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RevixEntities : DbContext
    {
        public RevixEntities()
            : base("name=RevixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Documentare> Documentare { get; set; }
        public virtual DbSet<Filme> Filme { get; set; }
        public virtual DbSet<Regizori> Regizori { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Toate> Toate { get; set; }
        public virtual DbSet<TvShows> TvShows { get; set; }
        public virtual DbSet<Utilizator> Utilizator { get; set; }
        public virtual DbSet<DistributieActori> DistributieActori { get; set; }
        public virtual DbSet<Distributie> Distributie { get; set; }
        public virtual DbSet<Seriale> Seriale { get; set; }
        public virtual DbSet<Recenzii> Recenzii { get; set; }
        public virtual DbSet<Actori> Actori { get; set; }
    }
}
