//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_revix
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seriale
    {
        public int IDSerial { get; set; }
        public int ID { get; set; }
        public Nullable<int> Nr_sezoane { get; set; }
        public string Gen { get; set; }
    
        public virtual Toate Toate { get; set; }
    }
}
